In [2]:
import numpy as np

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

Arrays are stored in contiguous memory locations, enabling faster computations

In [3]:
my_list=[12, 56,85, 63,47]
arr_1d = np.array(my_list)
print(f"Array Type : {type(arr_1d)}")
print(f"1d Array : {arr_1d}")

Array Type : <class 'numpy.ndarray'>
1d Array : [12 56 85 63 47]


In [4]:
# Two Dimensional Array
list_1 = [11, 22, 33, 44, 55]
list_2 = [15, 25, 35, 45, 65]
list_3 = [21, 31, 41, 51, 61]

arr_md = np.array([list_1, list_2, list_3])
print(f"Array Dimension: {arr_md.shape}")
print(arr_md)

# Reshape Array
arr_md_reshaped = arr_md.reshape(5, 3)
print(f'\nRehaped Array : {arr_md_reshaped}')

# For reshape number of Element has to be same
# e.g. 5 * 3 = 15
# 3 * 5  - Valid
# 1 * 15 - Valid
# 4 * 5 - Invalid

array_md_reshaped_2 = arr_md.reshape(1, 15)
print("\n", array_md_reshaped_2)

Array Dimension: (3, 5)
[[11 22 33 44 55]
 [15 25 35 45 65]
 [21 31 41 51 61]]

Rehaped Array : [[11 22 33]
 [44 55 15]
 [25 35 45]
 [65 21 31]
 [41 51 61]]

 [[11 22 33 44 55 15 25 35 45 65 21 31 41 51 61]]


In [5]:
# Indexing
arr_str = np.array(["Python", "Java", "C#", "Azure", 123])
print(arr_str[1]) # Access first index

Java


In [6]:
arr_md_2 = np.array([[11, 22, 33, 44, 55],
 [15, 25, 35, 45, 65],
 [21, 31, 41, 51, 61]])

print(arr_md_2[:,:]) # Print all rows and Columns
#print(arr_md_2[0,4]) # Print First Row and Fifth Column Value

print("\n\n", arr_md_2[0:2,:]) # First 2 rows and all third columns

print("\n\n", arr_md_2[0:2,1:3]) # First 2 rows and second and third columns


[[11 22 33 44 55]
 [15 25 35 45 65]
 [21 31 41 51 61]]


 [[11 22 33 44 55]
 [15 25 35 45 65]]


 [[22 33]
 [25 35]]


In [9]:
# To create an array of evenly spaced values within a given interval.
print(np.arange(1, 15, step=3))


[ 1  4  7 10 13]


In [ ]:
# Generate array of Evenly Spaced Numbers
# Generate 50 evenly spaced numbers between 1 and 100 (inclusive)
print(f"\n Array LinSpace : {np.linspace(1, 100, 50)}")


 Array LinSpace : [  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


# Broadvasting
The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. 

In [11]:
# Broadcasting Example
num_array_5 = np.array([[2, 3, 4], [6, 2, 7]]) # Shape (2, 3)
num_array_6 = np.array([[1, 4, 6]]) # Shape (3,)

# broadcsting allows the addition
print(np.add(num_array_5, num_array_6))


[[ 3  7 10]
 [ 7  6 13]]


In [17]:
# Copy function and broadcasting
num_array_8 = np.array([4, 7, 5, 2, 9, 25])
# From 3rd Index onwards replace values with 100
num_array_8[3:] = 100
print(num_array_8)

# Deep Copy.
num_array_88 = num_array_8
num_array_88[3:] = 200
print(f"\n\nNum Array 88: {num_array_88}")
# Update original array too. Because arrays are reference type.
print(f"\n\nNum Array 8: {num_array_8}")

# Shallow Copy Array
num_array_888 = num_array_8.copy()
num_array_888[3:] = 300
print(f"\n\nNum Array 8: {num_array_8}") # Wont update original
print(f"\nNum Array 8888: {num_array_888}")


[  4   7   5 100 100 100]


Num Array 88: [  4   7   5 200 200 200]


Num Array 8: [  4   7   5 200 200 200]


Num Array 8: [  4   7   5 200 200 200]

Num Array 8888: [  4   7   5 300 300 300]


In [ ]:
# conditions useful in exploratory Data Analysis
num_array_10 = np.array([0, 2, 3, 5, 8])

# if value less then 5 return True otherwise False
print(num_array_10 < 5) 

# Multiply each element by 2
print(num_array_10 * 2)

# Return all elements less then 5
print(num_array_10[num_array_10 < 5])

[ True  True  True False False]
[ 0  4  6 10 16]
[0 2 3]


In [29]:
num_array_zeros = np.zeros((5, 3))
print(f"\n Zero Array : {num_array_zeros}")

num_array_ones = np.ones((3, 2))
print(f"\n Ones Array: {num_array_ones}")

# Random Distribution
array_rand_1 = np.random.rand(4, 2)
print(f"\nRandom Array: {array_rand_1}")

# Generate a single random number from the standard normal distribution or Gaussian Distribution
array_rand_2 = np.random.randn(4,2)
print(f"\nRandom Array 2: {array_rand_2}")


 Zero Array : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Ones Array: [[1. 1.]
 [1. 1.]
 [1. 1.]]

Random Array: [[0.14823927 0.17427585]
 [0.69602367 0.76644373]
 [0.69056318 0.2249806 ]
 [0.40163289 0.58418596]]

Random Array 2: [[ 0.16193085 -1.20122826]
 [ 1.52516594  1.28641671]
 [ 2.25340771 -0.65019706]
 [ 0.05984552  0.33090825]]


In [32]:
# Int array, Select 20 numbers between 0 to 200 and create create array of shape (5, 4)
array_rand_int = np.random.randint(0, 100, 20).reshape(5, 4)
print(f"\nRandom Array Int: {array_rand_int}")

# Array of random float numbers between 0 and 1
array_rand_float = np.random.random_sample(8).reshape(2, 4)
print(f"\n Random Sample : {array_rand_float}")


Random Array Int: [[67 56 76 76]
 [54 96 91 38]
 [70 71 19 32]
 [98 57 70 22]
 [ 1 93 51 33]]

 Random Sample : [[0.50683188 0.58785362 0.20010252 0.82055765]
 [0.08065738 0.01274001 0.6765199  0.6747971 ]]
